import sys
import os

EXACT = [
   ('unapređenjima', 'unaprjeđenjima'),
    ('pravovercima', 'pravovjernima'),
    ('unapređenja', 'unaprjeđenja'),
    ('unapređenje', 'unaprjeđenje'),
    ('unapređenju', 'unaprjeđenju'),
    ('pravoverca', 'pravovjernog'),
    ('pravoverce', 'pravovjerne'),
    ('pravoverci', 'pravovjerni'),
    ('pravovercu', 'pravovjernom'),
    ('celinama', 'cjelinama'),
    ('doprineo', 'doprinio'),
    ('pretrpeo', 'pretrpio'),
    ('razboleo', 'razbolio'),
    ('verbalne', 'verbalne'),
    ('verbalne', 'verbalne'),
    ('verzija', 'verzija'),
    ('verzija', 'verzija'),
    ('zamenik', 'zamjenik'),
    ('celima', 'cijelima'),
    ('celina', 'cjelina'),
    ('celine', 'cjeline'),
    ('celini', 'cjelini'),
    ('celinu', 'cjelinu'),
    ('dedama', 'djedovima'),
    ('dedovi', 'djedovi'),
    ('drugde', 'drugdje'),
    ('najpre', 'najprije'),
    ('napred', 'naprijed'),
    ('nemima', 'nijemima'),
    ('rečima', 'riječima'),
    ('svideo', 'svidio'),
    ('uvideo', 'uvidio'),
    ('doneo', 'donio'),
    ('nigde', 'nigdje'),
    ('pevac', 'kokot'),
    ('rekao', 'rekao'),
    ('rekla', 'rekla'),
    ('rečju', 'riječji'),
    ('sreda', 'srijeda'),
    ('svest', 'svijest'),
    ('uspeo', 'uspio'),
    ('uspeo', 'uspio'),
    ('video', 'vidio'),
    ('vreme', 'vrijeme'),
    ('želeo', 'želio'),
    ('žudeo', 'žudio'),
    ('cela', 'cijela'),
    ('cele', 'cijele'),
    ('celi', 'cijeli'),
    ('celo', 'cijelo'),
    ('celu', 'cijelu'),
    ('dece', 'djece'),
    ('dede', 'djedovi'),
    ('dedi', 'djedi'),
    ('dedu', 'djedu'),
    ('dele', 'dijele'),
    ('dete', 'dijete'),
    ('hteo', 'htio'),
    ('leta', 'ljeta'),
    ('nem.', 'njem.'),
    ('neme', 'nijeme'),
    ('nemi', 'nijemi'),
    ('nemo', 'nijemo'),
    ('plen', 'plijen'),
    ('reka', 'rijeka'),
    ('reke', 'rijeke'),
    ('reko', 'rijeko'),
    ('reku', 'rijeku'),
    ('reči', 'riječ'),
    ('smeo', 'smio'),
    ('uvek', 'uvijek'),
    ('uvid', 'uvid'),
    ('vera', 'vjera'),
    ('vere', 'vjere'),
    ('veri', 'vjeri'),
    ('veru', 'vjeru'),
    ('vide', 'vide'),
    ('žele', 'žele'),
    ('bes', 'bijes'),
    ('ceo', 'cio'),
    ('ded', 'djed'),
    ('deo', 'dio'),
    ('dev', 'djev'),
    ('dve', 'dvije'),
    ('lek', 'lijek'),
    ('nem', 'nijem'),
    ('obe', 'obje'),
    ('pre', 'prije'),
    ('reč', 'riječ'),
    ('sme', 'smije'),
]



STEMS = [
    ('četvoromeseč', 'četvoromjeseč'),
    ('desetomeseč', 'desetomjeseč'),
    ('devetomeseč', 'devetomjeseč'),
    ('predstavnik', 'predstavnik'),
    ('jednomeseč', 'jednomjeseč'),
    ('pretpostav', 'pretpostav'),
    ('sedmomeseč', 'sedmmjeseč'),
    ('šestomeseč', 'šestomjeseč'),
    ('osmomeseč', 'osmoomjeseč'),
    ('petomeseč', 'petomjeseč'),
    ('podrazume', 'podrazumije'),
    ('presecanj', 'presijecanj'),
    ('presecanj', 'presijecanj'),
    ('bezuspeš', 'bezuspješ'),
    ('celobroj', 'cjelobroj'),
    ('doprinel', 'doprinijel'),
    ('doprinos', 'doprinios'),
    ('dragocen', 'dragocjen'),
    ('dvomeseč', 'dvomjeseč'),
    ('opredeli', 'opredijeli'),
    ('opredelj', 'opredjelj'),
    ('ponedelj', 'ponedjelj'),
    ('potpreds', 'potpredsj'),
    ('potpreds', 'potpredsj'),
    ('predvide', 'predvidje'),
    ('pregreja', 'pregrija'),
    ('pretrpel', 'pretrpjel'),
    ('ravnomer', 'ravnomjern'),
    ('tromeseč', 'tromjeseč'),
    ('verovatn', 'vjerovatn'),
    ('zakasnel', 'zakašnjel'),
    ('zaveštan', 'zavještan'),
    ('delegat', 'delegat'),
    ('delimič', 'djelimič'),
    ('izbegav', 'izbjegav'),
    ('letelic', 'letjelic'),
    ('nadžive', 'nadživje'),
    ('napredn', 'napredn'),
    ('napredo', 'napredo'),
    ('neizbež', 'neizbjež'),
    ('neizmer', 'neizmjer'),
    ('obavest', 'obavijest'),
    ('obavešt', 'obavješt'),
    ('obezbed', 'obezbijed'),
    ('obezbeđ', 'obezbjeđ'),
    ('ocenjiv', 'ocjenjiv'),
    ('odeljak', 'odjeljak'),
    ('osvedoč', 'osvjedoč'),
    ('osvetli', 'osvijetli'),
    ('osvetlj', 'osvjetlj'),
    ('podsmeh', 'podsmjeh'),
    ('pogreši', 'pogriješi'),
    ('poverlj', 'povjerlj'),
    ('povredi', 'povrijedi'),
    ('prebole', 'prebolje'),
    ('predlog', 'prijedlog'),
    ('premest', 'premjest'),
    ('premešt', 'premješt'),
    ('prethod', 'prethod'),
    ('primedb', 'primjedb'),
    ('primeni', 'primijeni'),
    ('primenj', 'primijenj'),
    ('procena', 'procjena'),
    ('procene', 'procjene'),
    ('proceni', 'procijeni'),
    ('procenj', 'procjenj'),
    ('procenu', 'procjenu'),
    ('prosleđ', 'prosljeđ'),
    ('rasejan', 'rasijan'),
    ('razbole', 'razbolje'),
    ('razmenj', 'razmjenj'),
    ('razume', 'razumije'),
    ('telefon', 'telefon'),
    ('umetnik', 'umjetnik'),
    ('unapređ', 'unapređ'),
    ('zabelež', 'zabiljež'),
    ('zahteva', 'zahtijeva'),
    ('zaplena', 'zapljena'),
    ('zaplene', 'zapljene'),
    ('zapleni', 'zaplijeni'),
    ('zaplenu', 'zapljenu'),
    ('bekstv', 'bjekstv'),
    ('decemb', 'decemb'),
    ('dedukt', 'dedukt'),
    ('delima', 'djelima'),
    ('delimi', 'djelimi'),
    ('detalj', 'detalj'),
    ('detinj', 'djetinj'),
    ('dodeli', 'dodijeli'),
    ('dodelj', 'dodjelj'),
    ('dospel', 'dospjel'),
    ('dožive', 'doživje'),
    ('gnezdo', 'gnijezdo'),
    ('izgore', 'izgorje'),
    ('izvesn', 'izvjesn'),
    ('izvest', 'izvijest'),
    ('menjač', 'mjenjač'),
    ('nalepn', 'naljepn'),
    ('namešt', 'namješt'),
    ('nasled', 'naslijed'),
    ('nasmeš', 'nasmiješ'),
    ('nedelj', 'nedjelj'),
    ('nemošć', 'nijemošć'),
    ('neretk', 'nerijetk'),
    ('neuspe', 'neuspje'),
    ('obelež', 'obiljež'),
    ('odeven', 'odjeven'),
    ('pešačk', 'pješačk'),
    ('pobedi', 'pobijedi'),
    ('pobegl', 'pobjegl'),
    ('podela', 'podjela'),
    ('podseć', 'podsjeć'),
    ('porekl', 'porijekl'),
    ('posled', 'posljed'),
    ('posred', 'posred'),
    ('povest', 'povijest'),
    ('povređ', 'povrijeđ'),
    ('predse', 'predsje'),
    ('predst', 'predst'),
    ('predst', 'predst'),
    ('preduz', 'preduz'),
    ('preseć', 'presjeć'),
    ('prevar', 'prevar'),
    ('preživ', 'preživ'),
    ('preživ', 'preživj'),
    ('primen', 'primjen'),
    ('primer', 'primjer'),
    ('proleć', 'proljeć'),
    ('promen', 'promjen'),
    ('prosek', 'prosijek'),
    ('proseč', 'prosječ'),
    ('prosle', 'proslije'),
    ('proter', 'protjer'),
    ('prover', 'provjer'),
    ('razmer', 'razmjer'),
    ('razreš', 'razriješ'),
    ('razume', 'razumje'),
    ('razume', 'razumije'),
    ('reklam', 'reklam'),
    ('rešenj', 'rješenj'),
    ('savest', 'savjest'),
    ('smatra', 'smatra'),
    ('stalež', 'stalež'),
    ('strelj', 'strijelj'),
    ('svetlo', 'svjetlo'),
    ('svetsk', 'svjetsk'),
    ('svugde', 'svugdje'),
    ('unapre', 'unaprije'),
    ('vaspit', 'vaspit'),
    ('verova', 'vjerova'),
    ('vremen', 'vremen'),
    ('zahtev', 'zahtjev'),
    ('zahtev', 'zahtijev'),
    ('zamenj', 'zamjenj'),
    ('zamenj', 'zamjenj'),
    ('zaplen', 'zaplijen'),
    ('zapose', 'zaposje'),
    ('zaposl', 'zapošlj'),
    ('beleg', 'biljeg'),
    ('belež', 'biljež'),
    ('celin', 'cjelin'),
    ('celog', 'cijelog'),
    ('cenit', 'cijeniti'),
    ('cveta', 'cvjeta'),
    ('decem', 'decem'),
    ('delat', 'djelat'),
    ('deleć', 'dijeleć'),
    ('delim', 'dijelim'),
    ('delić', 'djelić'),
    ('delić', 'delić'),
    ('detet', 'djetet'),
    ('devet', 'devet'),
    ('devoj', 'djevoj'),
    ('dodel', 'dodjel'),
    ('donel', 'donijel'),
    ('greja', 'grija'),
    ('greši', 'griješi'),
    ('izbeg', 'izbjeg'),
    ('izbeg', 'izbjeg'),
    ('izmen', 'izmijen'),
    ('izmer', 'izmjer'),
    ('izned', 'izned'),
    ('iznet', 'iznijet'),
    ('izveš', 'izvješ'),
    ('kolen', 'koljen'),
    ('kolev', 'kolijev'),
    ('koren', 'korijen'),
    ('lekar', 'ljekar'),
    ('lepot', 'ljepot'),
    ('lepot', 'ljepot'),
    ('letak', 'letak'),
    ('letnj', 'ljetnj'),
    ('levic', 'ljevic'),
    ('levič', 'ljevič'),
    ('mesec', 'mjesec'),
    ('namer', 'namjer'),
    ('napad', 'napad'),
    ('napad', 'napad'),
    ('nared', 'nared'),
    ('nared', 'nared'),
    ('nedel', 'nedjel'),
    ('negde', 'negdje'),
    ('nemac', 'njemac'),
    ('nemač', 'njemač'),
    ('nemoć', 'nemoć'),
    ('never', 'nevjer'),
    ('obole', 'obolje'),
    ('oceni', 'ocijeni'),
    ('ocenj', 'ocjenj'),
    ('odole', 'odolje'),
    ('opsed', 'opsjed'),
    ('oseća', 'osjeća'),
    ('osvet', 'osvjet'),
    ('pobeg', 'pobjeg'),
    ('podel', 'podijel'),
    ('podne', 'podne'),
    ('pomer', 'pomjer'),
    ('pomer', 'pomjer'),
    ('posed', 'posjed'),
    ('poset', 'posjet'),
    ('poseć', 'posjeć'),
    ('posle', 'poslije'),
    ('pover', 'povjer'),
    ('prene', 'prenije'),
    ('preti', 'prijeti'),
    ('rasej', 'rasijan'),
    ('savet', 'savjet'),
    ('sever', 'sjever'),
    ('smeja', 'smija'),
    ('smenj', 'smjenj'),
    ('smest', 'smjest'),
    ('smešt', 'smješt'),
    ('svedo', 'svjedo'),
    ('svide', 'svidje'),
    ('ubeđe', 'ubijeđe'),
    ('ucena', 'ucjena'),
    ('ucene', 'ucjene'),
    ('uceni', 'ucijeni'),
    ('ucenu', 'ucjenu'),
    ('umest', 'umjest'),
    ('usled', 'usljed'),
    ('uspeh', 'uspjeh'),
    ('uvežb', 'uvježb'),
    ('uvide', 'uvidje'),
    ('venac', 'vijenac'),
    ('veruj', 'vjeruj'),
    ('vetar', 'vjetar'),
    ('videl', 'vidjel'),
    ('volet', 'voljet'),
    ('zamen', 'zamijen'),
    ('zamer', 'zamjer'),
    ('zamer', 'zamjer'),
    ('zased', 'zasijed'),
    ('zaver', 'zavjer'),
    ('zvezd', 'zvijezd'),
    ('zvezd', 'zvjezd'),
    ('zvezd', 'zvijezd'),
    ('čovek', 'čovjek'),
    ('čoveč', 'čovječ'),
    ('želel', 'željel'),
    ('želet', 'željet'),
    ('živel', 'živjel'),
    ('živeo', 'živio'),
    ('živet', 'živjet'),
    ('žudel', 'žudel'),
    ('besn', 'bijesn'),
    ('besv', 'besvj'),
    ('beža', 'bježa'),
    ('bled', 'blijed'),
    ('breg', 'brijeg'),
    ('cena', 'cijena'),
    ('ceni', 'cijeni'),
    ('cent', 'cent'),
    ('cenu', 'cijenu'),
    ('cvet', 'cvijet'),
    ('deca', 'djeca'),
    ('deci', 'djeci'),
    ('deco', 'djeco'),
    ('decu', 'djecu'),
    ('deli', 'dijeli'),
    ('deča', 'dječa'),
    ('done', 'donije'),
    ('dvem', 'dvjem'),
    ('gnev', 'gnjev'),
    ('greh', 'grijeh'),
    ('hleb', 'hljeb'),
    ('leka', 'lijeka'),
    ('leko', 'ljeko'),
    ('leku', 'lijeku'),
    ('lenj', 'lijen'),
    ('leti', 'ljeti'),
    ('leto', 'ljeto'),
    ('letu', 'ljetu'),
    ('mese', 'mjese'),
    ('mesn', 'mjesn'),
    ('mest', 'mjest'),
    ('mlek', 'mlijek'),
    ('nemc', 'njemc'),
    ('nežn', 'nježn'),
    ('ocen', 'ocjen'),
    ('odel', 'odijel'),
    ('odel', 'odjel'),
    ('odeć', 'odjeć'),
    ('odne', 'odnije'),
    ('onde', 'ondje'),
    ('oset', 'osjet'),
    ('oseć', 'osjeć'),
    ('ovde', 'ovdje'),
    ('pesm', 'pjesm'),
    ('peva', 'pjeva'),
    ('peša', 'pješa'),
    ('peša', 'pješa'),
    ('retk', 'rijetk'),
    ('rečn', 'rječn'),
    ('reša', 'rješa'),
    ('reši', 'riješi'),
    ('seti', 'sjeti'),
    ('slep', 'slijep'),
    ('smeh', 'smijeh'),
    ('smel', 'smjel'),
    ('smer', 'smjer'),
    ('sneg', 'snijeg'),
    ('sten', 'stijen'),
    ('teme', 'tjeme'),
    ('tera', 'tjera'),
    ('tesn', 'tijesn'),
    ('ubed', 'ubijed'),
    ('ubeđ', 'ubjeđ'),
    ('unet', 'unijet'),
    ('unel', 'unijel'),
    ('uneš', 'uneš'),
    ('uspe', 'uspje'),
    ('uteh', 'utjeh'),
    ('uver', 'uvjer'),
    ('venc', 'vijenc'),
    ('venč', 'vjenč'),
    ('vero', 'vjero'),
    ('vers', 'vjers'),
    ('vest', 'vijest'),
    ('vetr', 'vjetr'),
    ('veća', 'veća'),
    ('veće', 'veće'),
    ('veći', 'veći'),
    ('vešt', 'vješt'),
    ('volj', 'volj'),
    ('vred', 'vrijed'),
    ('vređ', 'vrijeđ'),
    ('zver', 'zvijer'),
    ('žele', 'žele'),
    ('bed', 'bijed'),
    ('bel', 'bijel'),
    ('cep', 'cijep'),
    ('cev', 'cijev'),
    ('gde', 'gdje'),
    ('hte', 'htje'),
    ('lep', 'lijep'),
    ('les', 'ljes'),
    ('lev', 'lijev'),
    ('leč', 'liječ'),
    ('leš', 'lješ'),
    ('mer', 'mjer'),
    ('meš', 'mješ'),
    ('mle', 'mlje'),
    ('pes', 'pijes'),
    ('pev', 'pjev'),
    ('ređ', 'rjeđ'),
    ('reš', 'rješ'),
    ('sen', 'sjen'),
    ('seć', 'sjeć'),
    ('seć', 'sjeć'),
    ('tel', 'tijel'),
    ('vek', 'vijek'),
    ('več', 'vječ'),

]

if __name__ == "__main__":
    # Izbor liste za ažuriranje
    izbor = input("Koju listu želite da uvećate? Unesite 1 za EXACT ili 2 za STEMS: ").strip()
    
    if izbor == "1":
        izabrana_lista = EXACT
        naziv_liste = "EXACT"
    elif izbor == "2":
        izabrana_lista = STEMS
        naziv_liste = "STEMS"
    else:
        print("Greška: Nevažeći izbor! Prekid rada.")
        sys.exit()

    korisnicki_unos = input(f"Unesite parove riječi za {naziv_liste} odvojene razmakom (npr. reka rijeka det djet): ").strip()
    dijelovi = korisnicki_unos.split()

    # Provjera da li imamo paran broj riječi za formiranje parova
    if len(dijelovi) >= 2 and len(dijelovi) % 2 == 0:
        dodati_parovi = []
        
        # Prolazak kroz listu sa korakom 2 i kreiranje parova
        for i in range(0, len(dijelovi), 2):
            novi_par = (dijelovi[i], dijelovi[i+1])
            if novi_par not in izabrana_lista:
                izabrana_lista.append(novi_par)
                dodati_parovi.append(novi_par)
        
        if dodati_parovi:
            # Sortiranje: po dužini prve riječi opadajuće, pa abecedno
            izabrana_lista.sort(key=lambda x: (-len(x[0]), x[0]))
            
            with open("novaLista.txt", "w", encoding="utf-8") as f:
                # Upisivanje trenutnog stanja izabrane liste u fajl
                for stavka in izabrana_lista:
                    f.write(f"   {stavka}\n")
            
            print(f"\nUspješno dodati parovi u {naziv_liste}: {dodati_parovi}")
            print("Nova lista je upisana u 'novaLista.txt'!")
        else:
            print(f"\nSvi uneseni parovi već postoje u listi {naziv_liste}.")
    else:
        print("Greška: Morate unijeti paran broj riječi kako bi se formirali parovi!")

    if len(sys.argv) == 3: 
        # Pretpostavka da je funkcija obradi_datoteku definisana negdje u kodu
        if 'obradi_datoteku' in globals():
            obradi_datoteku(sys.argv[1], sys.argv[2])
